spring:
  application:
    name: loan-engine

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/prestloan}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis
    redis:
      key-prefix: "prestloan:"
      time-to-live: 10m

  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

app:
  security:
    username: ${APP_SECURITY_USERNAME}
    password: ${APP_SECURITY_PASSWORD}
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration-minutes: ${APP_JWT_EXPIRATION_MINUTES:120}
